mlnlffigen/ast-to-spec.sml

I replaced calls to `valty_nonvoid` in the `cft` function with a new function `fun_valty_nonvoid` that pattern matches on the result of `valty_nonvoid` and raises an exception if it's `Spec.STRUCT` or `Spec.UNION`. This aborts the assignment to the `gfuns` list in line 421. The exception handler uses the same `warnLoc` function used to warn about varargs.
Tested it on Ubuntu 14.10 64-bit using libsdl2's headers. *SDL_joystick.h* and *SDL_gamecontroller.h* are the ones with struct arguments/return values.

mlnlffigen no longer terminates because of structs

---

mlton/front-end/Makefile

Commit 4055a88 added post-processing with sed of generated front-end
files to support recent versions of SML/NJ's ml-lex and ml-yacc that
generate long identifiers rather than unqualified (top-level
environment) identifiers.
Unfortunately, GNU sed (e.g., linux) and BSD sed (e.g., darwin) differ
in the treatment of the "-i" (in place extension) command line flag,
which can lead one or the other to leave a backup file that dirties
the working tree.
Use "mv" and temporary files to eliminate the need for in place
editing.

Update post-processing of generated front-end files.

---

mlton/codegen/c-codegen/c-codegen.fun
mlton/main/main.fun
runtime/gc/init.c
runtime/gc/init.h

For a given compiler and input program (and compile-time options), deterministically build executable by:
* Eliminating output executable name from compile-time specified "@MLton" arguments.
* Deterministically generating magic constant.
Closes MLton/mlton#50.

Deterministic builds

---

doc/changelog
doc/examples/ffi/export.sml
doc/examples/ffi/test_quot.sml
doc/guide/src/CallingFromCToSML.adoc
doc/guide/src/CallingFromSMLToC.adoc
doc/guide/src/ForeignFunctionInterfaceSyntax.adoc
mlton/ast/ast-core.fun
mlton/ast/ast-core.sig
mlton/atoms/c-function.fun
mlton/atoms/c-function.sig
mlton/elaborate/elaborate-core.fun
mlton/front-end/ml.grm

Two updates to `_import` attributes for C function kinds:
* Introduce a `reentrant` `_import` attribute for `_import`-ed C functions that call `_export`-ed SML functions.
* Document the `pure`, `impure`, and `reentrant` `_import` attributes.
Fixes MLton/mlton#88 and MLton/mlton#89.

Updates to _import attributes for C function kinds.

---

basis-library/arrays-and-vectors/mono-array.fun
basis-library/arrays-and-vectors/mono-array2.fun
basis-library/arrays-and-vectors/mono-array2.sig
basis-library/arrays-and-vectors/mono-vector-slice.sig
basis-library/arrays-and-vectors/mono-vector.fun
basis-library/arrays-and-vectors/mono-vector.sig
basis-library/arrays-and-vectors/mono.sml
basis-library/arrays-and-vectors/sequence0.sml
basis-library/net/socket.sml
doc/changelog

* Hide type equality of mono and poly Word8.word arrays and vectors; fixes MLton/mlton#45.
* Hide equality status of poly (and mono) vector and array slices; fixes MLton/mlton#47.

Changes to type equalities and equality status in Basis Library.

---

lib/stubs/mlton-stubs/mlton.sml
lib/stubs/mlton-stubs/platform.sig
mlton/main/main.fun
runtime/platform/arm64.h

Patch from Edmund Evans via mlton-devel mailing list and Debian Bug
report (https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=762143) to
build on arm64 (aarch64) Debian unstable.
Original support for arm64 (aarch64) was commit 51ac878.

Further support for arm64 (aarch64).

---

Makefile
bin/mlton-script
runtime/Makefile

Use a WITH_GMP Makefile variable to specify the GMP location.  The GMP
location is propagated to the bin/mlton script.
Configuring the GMP location is only necessary if gmp.h and/or libgmp
are not found on the default include and/or library paths.
See MLton/mlton#134.

Configure GMP location via Makefile

---

lib/mlyacc-lib/lrtable.sml

Recent versions of SML/NJ (and, hopefully, future versions of MLton)
have implemented proposed Basis Library improvements, including adding
`List.sub` as an alias for `List.nth`.  In the MLYacc library, a
declaration of the form
open Array List
results in `List.sub` shadowing `Array.sub`, leading to subsequent type
errors at the use of `sub`.  As the only unqualified name needed is
`sub`, replace the declaration with
val sub = Array.sub
as has been done in the SML/NJ sources (see
https://smlnj-gforge.cs.uchicago.edu/scm/viewvc.php?view=rev&root=smlnj&revision=4133).

Remove use of open in lrtable.sml of MLYacc lib

---

runtime/gc/signals.c

Commit 6435e0e erroneously passed the `prot` as the last, rather than
the third, argument to GC_mmapAnon_safe_protect.

Fix args to GC_mmapAnon_safe_protect

---

bin/add-cross
doc/guide/src/PortingMLton.adoc

Successfully bootstrapping MLton on Fedora aarch64 required two sets of changes that I have put in this pull request.
1. add-cross should set the $PATH variable in a more robust way. Using dirname to set the $PATH of the bin directory, when add-cross is invoked from the bin directory itself, results in '.' being added to $PATH. This causes add-cross to fail. Using a relative path from "$src" picks up the full path of the bin directory from pwd.
2. The documentation neglects to mention two steps. The first is the copying of all relevant includes to the target machine. The second is a complexity in bootstrapping mlyacc. Note that the changes I made to the documentation presuppose that the includes in build/lib/include, and the files mlyacc/src/mlyacc.grm.*, are all architecture-independent. …

Fixes to bootstrapping script and documentation

---

basis-library/text/char0.sml
bin/regression
doc/guide/src/MLBasisAnnotations.adoc
doc/guide/src/SuccessorML.adoc
doc/guide/src/Unicode.adoc
mlton/control/control-flags.sig
mlton/control/control-flags.sml
mlton/elaborate/elaborate-mlbs.fun
mlton/front-end/ml.grm
mlton/front-end/ml.lex
mlton/front-end/mlb.lex
mlton/main/main.fun

* Add an `allowSuccessorML {false|true}` MLB annotation to enable all Successor ML features with a single annotation.  Closes MLton/mlton#143.
* Fix parsing of numeric labels to only accept an INT token that does not begin with 0, is not an extended literal, is not negative, and is decimal.
* Drop the alternate word prefixes (`0xw` and `0bw`).
* Unconditionally allow line comments in MLB files.
* Allow UTF-8 byte sequences in text constants.  Closes MLton/mlton#117.
* Refactor ml.lex and mlb.lex to be more maintainable.
* Rename `allowRecPunning` annotation to `allowRecordPunExps`.
* Update documentation.

Various SuccessorML updates

---

mlton/front-end/ml.lex

When files were encoded with Windows-style `\r\n` line endings, we were
incorrectly including the `\n` when computing the column number.
Closes #170.
I'm not sure if there are automated tests; if there are, I'd be glad to add a
test for this change.
Regardless, it builds and fixes the issue locally for me (according to the
"Steps to Reproduce" in #170).

Correct off-by-one error in column numbers

---

lib/mlton/basic/directed-graph.sig
lib/mlton/basic/directed-graph.sml
lib/mlton/basic/dot.sml
lib/mlton/basic/error.sig
lib/mlton/basic/error.sml
lib/mlton/basic/exn.sml
lib/mlton/basic/exn0.sml
lib/mlton/basic/layout.sig
lib/mlton/basic/layout.sml
lib/mlton/basic/process.sml
mlton/backend/backend.fun
mlton/backend/live.fun
mlton/backend/rssa.fun
mlton/backend/rssa.sig
mlton/control/control.sml
mlton/main/main.fun
mlton/ssa/analyze.fun
mlton/ssa/analyze2.fun
mlton/ssa/prepasses.fun
mlton/ssa/shrink.fun
mlton/ssa/shrink2.fun
mlton/ssa/ssa-tree.fun
mlton/ssa/ssa-tree.sig
mlton/ssa/ssa-tree2.fun
mlton/ssa/ssa-tree2.sig
mlton/ssa/type-check.fun
mlton/ssa/type-check2.fun

Highlights:
* Display more context when reporting SSA and SSA2 IR type errors. A simple `Analyze.coerces` or `Reference to <x> not in scope` is not particularly illuminating.  Now the containing statement or transfer, the containing block label, and the containing function name are appended to the error message (6bee991).
* Add `-layout-width <n>` compile time expert option to control the target width for the pretty printer (d93db6f).
* Make cosmetic improvements to SSA and SSA2 IR display:
* Uses of global variables bound to small constants and conapps are commented with the corresponding value (50070b6).
* Include loop forest, along with control-flow graph and dominator tree, for functions with `-keep dot` (58502c8, 19e385d).
* Fix Ssa.PrePasses.breakCriticalEdges for codeMotion …

Updates to SSA, SSA2, and RSSA IR support infrastructure

---

lib/mlton/basic/sources.cm
lib/mlton/basic/sources.mlb
lib/mlton/basic/stream-parser.fun
lib/mlton/basic/stream-parser.sig
lib/mlton/basic/stream-parser.sml
lib/mlton/basic/stream.sig
lib/mlton/basic/stream.sml
lib/mlton/sources.cm
lib/mlton/sources.mlb
mlton/atoms/hash-type.fun
mlton/atoms/hash-type.sig
mlton/atoms/prim-tycons.fun
mlton/atoms/prim-tycons.sig
mlton/atoms/prim.fun
mlton/atoms/prim.sig
mlton/elaborate/elaborate-env.fun
mlton/elaborate/interface.fun
mlton/elaborate/interface.sig
mlton/elaborate/type-env.fun
mlton/main/compile.fun
mlton/main/compile.sig
mlton/main/main.fun
mlton/xml/parse-sxml.fun
mlton/xml/parse-sxml.sig
mlton/xml/sources.cm
mlton/xml/sources.mlb
mlton/xml/xml-tree.fun

This branch consists of two sets of larger additions, and one minor change to MLTon (the last depending on the first two):
1. Adds the StreamParser structure
This comes with other small additions to basic
2. Changes the compilation step to be split up slightly. This is a relatively small change, but deserves scrutiny
2. Adds the ParseSxml structure and the sxml file type to the compilation.
1.This is done, but there may be improvements that can be made to the parsing interface and its interaction with files and streams. At the moment it takes a stream, but there may be a way to improve the interface between it and Instream, or between Instream and Stream. In addition to StreamParser, two functions are added to Stream, firstNSafe (that takes as many it can get if it reaches the end) and …

Stream parsers + Sxml input

---

lib/mlton/basic/stream-parser.sig
lib/mlton/basic/stream-parser.sml
mlton/xml/parse-sxml.fun

Fixes the parser so that it can successfully parse mlton. This also changes the type/semantics of stream-parser.compose (so that it can now return 0 or more characters with each parse, rather than exactly 1)

Better stream transformers

---

mlton/main/main.fun

Because it is relatively cheap to support PIC in AMD64, it has become the default in many Linux distros. Given that there is no way to turn on or off PIC generation in MLton through command lines or mlb files (yet), I think it makes more sense to force PIC generation on AMD64.

Force PIC generation on AMD64.

---

runtime/gc/array.c

I can't build master on the latest macOS. It says `types mismatch`.

Fix the type of GC_arrayCopy

---

mlton/main/compile.fun

The bug was introduced by 7ca7629, which refactored some of
`main/compile.fun` to facilitate parsing and compiling with .sxml
programs.
The commit nicely factored out the code to setup runtime constants and
ran it before initiating compilation of .sml/.mlb or .sxml programs.
What is not apparent from the code in `main/compile.fun` is that
`LookupConstant.load` implicitly initializes some other constants.  In
particular, it initializes the `MLton_FFI_numExports` constant, which
in turn, is set by `Ffi.numExports ()`, which is itself a derived
value of the program being compiled (essentially, counting the number
of `_export` expressions in the program).  The laziness of CoreML
constants is precisely to support this derived constant (and,
potentially, others that might be a property of the …

Fix bug with compiling programs with `_export`-ed functions

---

lib/mlton/basic/popt.sig
lib/mlton/basic/popt.sml
lib/mlton/basic/quick-sort.sml
lib/mlton/basic/random.sml
mlton/backend/backend.fun
mlton/control/control-flags.sig
mlton/control/control-flags.sml
mlton/main/main.fun
mlton/ssa/simplify.fun
mlton/ssa/simplify2.fun

As has been well documented, seemingly trivial aspects of an experimental setup and/or a compiled program (for example, code placement) can have non-trivial impact on behavior (for example, run time).
A new MachineShuffle pass can be run after generating the MachineIR program.  This pass simply shuffles the collection of chunks within the program and shuffles the collection of blocks within a chunk.  Combined with a new `-seed-rand <w>` compiler option, this can yield distinct code placements.
Results in 40455fa.

Machine shuffle

---

mlton/ssa/restore.fun
mlton/ssa/restore2.fun

The flood of Restore diagnostics can obscure the diagnostic from the
invoking pass.

Suppress diagnostics in Restore{,2} pass

---

mlton/control/control-flags.sig
mlton/control/control-flags.sml
mlton/main/main.fun

A useful technique for developing optimization passes is to limit the
number of transformations made according to some finite "fuel".  The
particular transformation that triggers a bug or a performance change
can be found by binary-searching through the space of
fuels (`-opt-fuel 0` when the bug does not occur and `-opt-fuel 1000`
when the bug does occur).
A `val Control.optFuelAvailAndUse: unit -> bool` is also provided.
By default, if `-opt-fuel` is not given, then "infinite" fuel is
assumed.

Add `-opt-fuel <n>` expert compile-time option

---

Makefile.in

MLton/mlton#185 replaced the `-drop-pass <re>` compile-time option
with `-disable-pass <re>`, but these Makefile targets were not
updated.

Fix `debugged` and `traced` Makefile targets

---

configure.ac

MLton does not require a C++ compiler.

Drop `AC_PROG_CXX` from `configure.ac`

---

mlton/backend/ssa-to-rssa.sig

This is the idiom used elsewhere in the compiler, rather than sharing
individual sub-structures of `Atoms`.

In `signature SSA_TO_RSSA_STRUCTS` share by `Rssa.Atoms = Ssa.Atoms`

---

runtime/gc/heap_predicates.c
runtime/gc/invariant.c
runtime/gc/object-size.c
runtime/gc/object-size.h
runtime/gc/virtual-memory.c

Previously, the `isPointerInOldGen` and `isPointerInNursery`
predicates checked that the object pointer is strictly less than
`s->heap.start + s->heap.oldGenSize` and `s->frontier`, respectively.
With MLton/mlton#219 (forward pointer in header), 0-byte objects are
allowed and the above checks are insufficient.  In particular,
immediately after allocating a 0-byte object, the object pointer is
equal to the frontier.
Now, the `isPointerInOldGen` and `isPointerInNursery` predicates are
revised to check that the end of the object is less than or equal to
`s->heap.start + s->heap.oldGenSize` and `s->frontier`, respectively.

Fix heap invariant predicates

---

Makefile.in

Removed `$PREFIX` and `$prefix` to allow the --prefix argument passed by the user to be honored.
Platform specific code was also removed since from the commit history it appears to predate the switch to autotools and a configurable `--prefix`.
Tested on Ubuntu. Needs tested on other platforms.

Remove $PREFIX and $prefix

---

.travis.yml
Dockerfile
Makefile.in
README.md
bin/run-docker

Added a simple Dockerfile which can be used to create an image with MLton built and installed on an ubuntu container. The build will be completed using the ubuntu provided **mlton** and **mlton-tools** packages.
The default entry point for the generated container image is to run the regression tests via **make check**.

Added a Dockerfile

---

configure.ac
mlton/codegen/c-codegen/c-codegen.fun
mlton/main/main.fun
runtime/cenv.h
runtime/gen/gen-types.c

Recent versions of glibc have complained about defining both `_BSD_SOURCE` and `_POSIX_C_SOURCE`, suggesting that that combination should be enabled by `_DEFAULT_SOURCE`, which is the default.  On Fedora (though, not (yet) Ubuntu), this leads to many warning messages during compilation of the runtime.
Would like to drop `-std=gnu99` and use compiler default, but MLton does require C99 (or greater) to compile the runtime system and gcc 4.8.4 on Ubuntu 14.04 (as provided by TravisCI) defaults to `-std=gnu90`.

Drop feature macros

---

lib/mlton/basic/layout.sig
lib/mlton/basic/layout.sml
mlton/control/control-flags.sig
mlton/control/control-flags.sml
mlton/elaborate/elaborate-env.fun
mlton/elaborate/elaborate-env.sig
mlton/main/compile.fun
mlton/main/main.fun

New functionality for `-show-basis`:
- `-show-basis-flat`: Recursively expand structures in environment, displaying components with long identifiers.  For example,
```
structure Z:
sig
datatype t = Z1 | Z2 of Z.t (* = datatype Z.t *)
val toString: Z.t -> string
end
datatype Z.t = Z1 | Z2 of Z.t (* = datatype Z.t *)
con Z.Z1: Z.t
con Z.Z2: Z.t -> Z.t
val Z.toString: Z.t -> string
```
Note that with `-show-basis-flat true`, value identifiers with constructor status are show as `con <vid>: <ty>` (rather than being omitted), and value identifiers with exception status are show as `exn <vid>: [<ty> ->] exn` (rather than as `exception <vid> [of <ty>]`).
- `-show-basis-def`: Appends `(* @ <region> *)` annotations to items in shown environment.
- `-show-basis-compact`: Tries to optimize vertical …

Updates to -show-basis

---

CHANGELOG.adoc
mlton/main/main.fun

Some projects use `-drop-pass` to avoid performance problems with DeepFlatten
and RefFlatten; see https://github.com/search?p=1&q=%22-drop-pass%22&type=Code.
Restoring `-drop-pass` avoids unnecessarily breaking these projects.

Restore, but deprecate, `-drop-pass` compile-time expert option.

---

CHANGELOG.adoc
basis-library/arrays-and-vectors/sequence.fun

Previously, `Sequence.{concat,concatWith}` operated by performing a `List.map` on the input, converting (full) sequences to slices, and `Sequence.{tokens,fields}` operated by performing a `List.map` on the output, converting slices to (full) sequences.  This unnecessarily allocated and traversed an intermediate list.
We introduce `Sequence.Slice.{concat,concatWith,tokens,fields}Gen` functions that take either a `toSlice` or a `fromSlice` function to convert the input or output.  For example, we now have:
fun Sequence.Slice.concat sls = Sequence.Slice.concatGen (sls, fn sl => sl)
fun Sequence.concat seqs = Sequence.Slice.concatGen (seqs, Sequence.Slice.full)
Note that the two uses of `Sequence.Slice.concatGen` are at different (polymorphic) types.  So, the two uses will be monomorphised to …

Avoid `List.map` in some `functor Sequence` fns of Basis Library

---

bin/clean

Old(er) vesions of Bash (e.g., OSX on TravisCI) do not support associative
arrays.

Use indexed, rather than associative, Bash array in `./bin/clean`

---

bin/mlton-script

Fix definitions of `gmp{CC,Link}Opts` in `./bin/mlton-script`

---

mllex/macros.hva
mlyacc/doc/macros.hva

Commit 8c6bc7e40 dropped HTML documentation for mllex and mlyacc, but forgot to
remove the hevea macros files.

Delete unnecessary files

---

runtime/Makefile

Link search directories are not necesary for compiling the runtime system, which
only compiles (and does not link).  Some C compilers (e.g., clang) issue a
"warning: argument unused during compilation: '-L<path>'".

Drop `-L$(WITH_GMP_LIB_DIR)` from `XCFLAGS` in `./runtime/Makefile`

---

Makefile
Makefile.binary
bin/mlton-script

Some systems (e.g., x86_64 Fedora) want to install the library files in `/usr/lib64`, rather than `/usr/lib`.  Thus, when installing it is necessary to compute and set the relative path of `TLIB` to `TBIN` when installing `$(TBIN)/mlton`.

Set relative path of library directory to binary directory  when installing mlton script

---

lib/mlton/basic/vector.fun
lib/mlton/basic/vector.sig
mlton/atoms/int-size.fun
mlton/atoms/word-size.fun
mlton/backend/rssa.fun
mlton/backend/ssa-to-rssa.fun
mlton/elaborate/elaborate-env.fun

Introduced Vector.toListKeepAllMap for an efficiency improvement over Vector.toList(Vector.keepAllMap(...)). Replaced usages with the new function.

Implementation for Vector.toListKeepAllMap

---

mlton/codegen/amd64-codegen/amd64-mlton.fun
mlton/codegen/x86-codegen/x86-mlton.fun

Uses of these functions were removed by b068814.

Remove unused functions

---

lib/mlton/basic/hash-table.sig
lib/mlton/basic/hash-table.sml
lib/mlton/basic/hash.sig
lib/mlton/basic/hash.sml
lib/mlton/basic/sources.cm
lib/mlton/basic/sources.mlb
lib/mlton/sources.cm
lib/mlton/sources.mlb
mlnlffigen/sources.mlb
mlton/atoms/hash-type.fun
mlton/atoms/profile-exp.fun
mlton/ssa/common-subexp.fun
mlton/ssa/known-case.fun
mlton/ssa/parse-ssa.fun
mlton/ssa/parse-ssa2.fun
mlton/ssa/restore.fun
mlton/ssa/restore2.fun
mlton/ssa/share-zero-vec.fun
mlton/ssa/ssa-tree.fun
mlton/ssa/ssa-tree2.fun
mlton/xml/monomorphise.fun

This patch adds the structures Hash and HashTable. Several, but not all, existing passes have been made to use these structures, generally reducing code size.
HashTable serves as a wrapper to offer a simpler interface for the common usage of HashSets as key-value mappings.
Hash offers operations to combine word hashes. I've tested on self-compiles and speed of hashing appears relatively unchanged. It always uses a Foller-No-Voll-style hash (multiply then xor) everywhere. When updating all locations correctly, there does not seem to be a significant speed difference (from an unscientific test, <0.5% of pre-codegen time on a self-compile).

Add HashTable and Hash structures and use in code

---

mlton/atoms/prim.fun

A cut-n-paste error had `x -? x` returning `0`, rather than `false`.
Closes MLton/mlton#294 (introduced by 11c33d8).

Fix bug in simplification of `x -? x`

---

mlton/backend/rssa.fun
mlton/backend/rssa.sig
mlton/backend/switch.fun
mlton/backend/switch.sig

All blocks with 0 occurences are deleted.
All blocks which do nothing but pass their arguments to another block are replaced by jumping to the target block (Most cases are 0 arguments, this handles the exact arguments in the same order for simplicity, which I did notice for some larger argument sets).
Specifically, it is those blocks which perform a fan-in that this would catch but not the inliner.
In theory there may be a block in this case which does nothing but profiling. There's no safe way to handle that that doesn't, but I don't imagine it's an issue in practice.
Here's a few quick sanity benchmarks. Most programs get a good improvement in size and compile time (and should also have improved RSSA output readability, which was half of the reason I wanted this). Boyer gets a 40% …

Slightly improved rssa shrink

---

mlton/backend/backend.fun

Fix a bug that was introduced by 136f3573c and triggered by the RedPRL program.
An unused `Jump` block argument would not be assigned a location, but the translation of a `Goto` transfer to that block would demand the location (resulting in an uncaught `Option` exception).  The fix is straightforward: only copy the actual arguments that correspond to formal arguments that are used.
Also simplify the code to generate the prologue of `Cont` and `Handler` blocks.

Fix MLton/mlton#305

---

include/c-common.h

The `stackTop` and `frontier` arguments should be `CPointer`, not `Pointer`.

Fix `Chunk<N>` prototype

---

mlton/ssa/ssa-tree2.fun

Ref may imply that the field is separately boxed,
whereas in the SSA2 IR, boxing is separate from mutability,
and is instead indicated by 'tuple' or another object type.
This should make the SSA2 object types easier to read correctly.

Change mutability keyword for SSA2 IR from 'ref' to 'mut'.

---

basis-library/mlton/thread.sml
basis-library/primitive/prim-mlton.sml
include/amd64-main.h
include/c-main.h
include/x86-main.h
mlton/atoms/ffi.fun
runtime/gc/gc_state.c
runtime/gc/gc_state.h

Instead, introduce a `pointer callFromCOpArgsResPtr` field in `struct
GC_state`.  This makes the value per gcState, which minimizes the diff
between MLton and the CMU MultiMLton project.

Eliminate global `MLton_FFI_opArgsResPtr`

---

regression/size.rep32a4.ok
regression/size.rep32a8.ok
regression/size.rep64a4.ok
regression/size.rep64a8.ok
regression/size.sml
runtime/gc/share.c
runtime/gc/size.c

`GC_size` and `GC_share` can be called with object-pointer-sized but non-pointer values (e.g., the `NONE` variant of a `int list option`).

Fix bug in `GC_{share,size}` with non-pointer roots

---

basis-library/system/io.sml

Closes MLton/mlton#326.
See https://sourceforge.net/p/mlton/mailman/message/36490863/.

Do not implement `OS.IO.poll` as a restartable system call

---

Makefile.binary
mlton/control/control-flags.sml
mlton/main/main.fun

If the C compiler's default behavior with respect to position-independent code/executables is different between the machine that built a binary release and a machine that uses a binary release, then there could be link-time errors when using the compiler.  In particular, if the machine that built the binary release defaults to `-fno-pie` (i.e., non-position independent), but the machine that uses the binary release defaults to `-pie` (i.e., position independent executable), then the link will fail (with a `relocation` error and a suggestion from the linker to recompile with `-fPIC`).
The `update` target of the `Makefile.binary` now detects the default behavior of the C compiler on the machine using the binary release and appropriately resets the `default::{pie,pic}` values in the …

Reset position-independent style defaults with `update` target of `Makefile.binary`

---

CHANGELOG.adoc
mlton/ssa/simplify-types.fun

`SimplifyTypes` could fail with a `no varInfo property` internal compiler error.  `SimplifyTypes` transforms each function by visiting the blocks via `Function.dfs`.  When visiting a statement, `setVarInfo` is called for the defined variable.  However, after identifying an unreachable statement (e.g., the `ConApp` of a `Useless` constructor), `SimplifyTypes` does not visit the remaining statements of the block.  When continuing with the DFS, `SimplifyTypes` may subsequently visit a block that use variables that were defined (but not visited and, therefore, not `setVarInfo`-ed) by a previously visited block.
This potential error was previously noted (see the comment at the end of MLton/mlton@19b07c0) and has now been observed in the wild (see MPLLang/mpl#107).
To fix the error, switch from …

Fix SimplifyTypes SSA optimization pass

---

mlton/atoms/atoms.fun
mlton/atoms/atoms.sig
mlton/atoms/prod.fun
mlton/atoms/prod.sig
mlton/atoms/sources.cm
mlton/atoms/sources.mlb
mlton/backend/backend-atoms.fun
mlton/backend/backend-atoms.sig
mlton/backend/backend.fun
mlton/backend/collect-statics.fun
mlton/backend/implement-profiling.fun
mlton/backend/limit-check.fun
mlton/backend/machine.fun
mlton/backend/object-type.sig
mlton/backend/object.fun
mlton/backend/object.sig
mlton/backend/packed-representation.fun
mlton/backend/rep-type.fun
mlton/backend/rep-type.sig
mlton/backend/representation.sig
mlton/backend/rssa-type-check.fun
mlton/backend/ssa2-to-rssa.fun
mlton/codegen/c-codegen/c-codegen.fun
mlton/control/bits.sml
mlton/control/control-flags.sig
mlton/control/control-flags.sml
mlton/main/main.fun
mlton/ssa/ssa-tree2.fun
mlton/ssa/ssa-tree2.sig
regression/flat-array.4.sml

Change:
datatype OBJECT_TYPE.t =
Normal of {hasIdentity: bool,
ty: ty}
| Sequence of {elt: ty,
hasIdentity: bool}
| Stack
| Weak of ty option (* in Weak (SOME t), must have Type.isObjptr t *)
to
datatype OBJECT_TYPE.t =
Normal of {components: ty Prod.t,
hasIdentity: bool}
| Sequence of {components: ty Prod.t,
hasIdentity: bool}
| Stack
| Weak of ty option (* in Weak (SOME t), must have Type.isObjptr t *)
With this change, the backend is able to be less conservative about
placing static objects in the `Dynamic` heap (b39a8f84c) and the RSSA
type checker can verify that updates via object offsets are of mutable
components (f72b174be).

Refactor RSSA/Machine object types

---

basis-library/text/char.sig
basis-library/text/char.sml
basis-library/text/string.sml
regression/string.fromString.ok
regression/string.fromString.sml
regression/string.sml

In [basis](http://sml-family.org/Basis/string.html#SIG:STRING.scan:VAL) description, `String.scan` retuns `NONE` if first character is non-printable.
But, `String.scan` in MLton returns `SOME ([], restStream)` now.
This PR is adding checking whether return value is nil or not.
```sml
val () =
let
(* scan starting '\n' that is not printable character *)
val result = String.scan Substring.getc (Substring.full "\n")
in
case result of
NONE => print "NONE\n"
| SOME (str, _) => print ("SOME:" ^ str ^ "\n")
end
```
```
NONE
```
Actual
```
SOME:
```

Fix String.scan to return NONE

---

doc/guide/src/ConcurrentMLImplementation.adoc
lib/cml/core-cml/channel.sml
lib/cml/core-cml/event.sml
lib/cml/core-cml/run-cml.sml
lib/cml/core-cml/scheduler.sml

When no base event in a CML synchronization is enabled, then all base events must be blocked.  It is important that all of the `blockFn`s are executed atomically (along with the prior work of synchronization), but the previous implementation briefly left the critical section as it switched from the thread that executed one `blockFn` to the next.  This would allow the timer interrupt to switch to another CML thread, without executing all of the `blockFn`s; the switched-to thread could initiate a synchronization that doesn't properly see the effect of the switched-from thread's `blockFn`s.
As a concrete example, consider a receiver thread that performs `CML.select (List.map CML.recvEvt chs)`; that is, it synchronizes on the choice of receiving from any channel in a list of channels. …

Fix bug in running `blockFn`s for `CML.sync`

---

lib/mlrisc-lib/MLRISC.patch
lib/smlnj-lib/smlnj-lib.patch

The SML/NJ Library is now used to compile mllex

Fix top-level `Overflow` in SML/NJ Library

---

doc/guide/src/Release20200722.adoc

* Original amd64-darwin packages are 19.6 (Catalina),
not 17.7 (High Sierra)
* Added amd64-darwin-17.7 (High Sierra) binary packages

Update Release20200722 with binary packages

---

CHANGELOG.adoc
doc/guide/src/Bugs20200722.adoc
mlton/backend/rssa-shrink.fun
mlton/backend/rssa-tree.fun
mlton/backend/rssa-tree.sig

Previously, `RssaShrink` could fail with a `no RssaShrink.replaceVar property` internal compiler error.  Consider the following:
```
L_K (x) Cont =
L_1 (x)
L_1 (y) Jump =
loop (y)
loop (z) Jump =
...
L_2 (...) Jump =
...
a = y
...
```
L_1 was identified as a candidate for jump chaining and the `goto L_1 (x)` in L_K was replaced by `goto loop (x)`:
```
L_K (x) Cont =
loop (x)
loop (z) Jump =
...
L_2 (...) Jump =
...
a = y
...
```
This results in an unbound variable `y`.  (In practice, it led to a `Fail: y has no RssaShrink.replaceVar property`, because no binding occurrence of `y` was encountered before the use during the transformation.)
Now, an occurrence count is calculated for each variable and a block is a candidate for jump chaining only if all of its arguments have an occurrence …

Fix bug in `RssaShrink`

---

mlton/control/control-flags.sml
mlton/main/main.fun

Avoid defaulting to native codegen on x86-darwin
The C compiler on x86-darwin defaults to producing position independent code, but the x86 codegen does not properly support x86-darwin PIC.
x86-darwin barely exists as a platform anymore.  It may be possible to get the old behavior by compiling with `-codegen 86 -pi-style npi`, but this is untested.

Fix for x86-darwin

---

runtime/platform/solaris.c

Use standard mmap implementation on Solaris
Previously, a non-standard implementation of `GC_{mmapAnon{,Flags,Stack},release}` was used on Solaris to work around (ancient) Solaris 5.7 issues.  Recent versions of Solaris would appear to support MAP_ANON and a -1 file descriptor.

Fix for solaris

---

runtime/platform/linux.c

Due to the `#define _GNU_SOURCE`, the constant is defined by
`sys/mman.h`.

Don't `#define MREMAP_MAYMOVE` in `runtime/platform/linux.c`

---

lib/mlnlffi-lib/Makefile
mlton/codegen/amd64-codegen/amd64-generate-transfers.fun
package/msys2/dlfcn.h

Two minor changes to make mlton compile on mingw.   To clarify, the "mingw" environment we target consists of mingw64 (a fork of the original mingw project) and msys2 (a fork of the original msys project).  mingw64 offers gcc for windows and many other build tools.  msys2 offers a unix-like shell on windows (using mingw64) and a package manager.
. in codegen/amd64-codegen/amd64-generate-transfers.fun, use "__imp_" instead of "_imp__" to access imported functions.  Left cygwin unchanged to use "_imp__".
. when building mlnlffigen, the dlfcn.h header file is missing in the target mingw environment.  We therefore created a package/msys2 directory to contain the header file and modified mlton/lib/mlnlffi-lib/Makefile to add this folder to the include path when compiling on mingw.

Mingw fixes

---

CHANGELOG.adoc
runtime/gc/dfs-mark.c

During a DFS marking, a weak object should only be linked if its objptr field is a valid object pointer (and not `BOGUS_OBJPTR`).
This bug was introduced by commit ec2a3afa2, which changed `is{Objptr,Pointer}` predicates to `is{Objptr,Pointer}InHeap` predicates.  This was motivated by the introduction of static heaps, because objects in the static heaps are not traced; in particular, objects in the immutable static heap are in read-only memory, and therefore cannot be marked and unmarked.
However, the semantics of these predicates are subtly different.  The `is{Objptr,Pointer}InHeap` return `TRUE` when the argument is a non-pointer (i.e., when `is{Objptr,Pointer}` returns `FALSE`).
Commit 2d46cc122 fixed many of the `isPointerInHeap(p)` predicates to `isPointer(p) and isPointerInHeap(p)`, …

Fix bug in handling of weak objects during mark-compact GC

---

CHANGELOG.adoc
mlton/Makefile
mlton/ssa/simplify-types.fun

19b07c03f attempted to fix a bug in `SimplifyTypes` related to `MLton_bogus` primitives added by `Useless`.  The essence of the bug is that is not appropriate to conclude that a tycon has cardinality `Zero` (e.g., if it is simplified to the point where it has no constructors) when a "value" of the tycon is created by `MLton_bogus`.
19b07c03f simply forced any tycon used with `MLton_bogus` to have cardinality `Many`.  However, such a tycon might have all constructors eliminated and will be marked to be replaced by the `void` type.  In turn, other types that use the tycon will be retained (with cardinality `Many`), but an `Option` exception would be raised by `simplifyUsefulTypes`, which assumes that all components are really useful (and non-`void`).
This PR adjusts things to force any …

Fix bug in SimplifyTypes SSA optimization pass

---

CHANGELOG.adoc
Makefile.binary

Properly detect default position-independent style in `Makefile.binary`

---

mlton/control/control-flags.sml

feed the flags to gcc separately, to fix this error:
`gcc: error: unrecognized command-line option '-fPIE -pie'`

fix option '-pi-style pie'

---

runtime/Makefile

The "shortest stem" rule for choosing a pattern rule was added in GNU
Make 3.82 (https://lists.gnu.org/archive/html/info-gnu/2010-07/msg00023.html),
but MacOS is stuck on the (ancient) GNU Make 3.81, which uses
definition order priority.

Use static pattern rule for bootstrap compilation

---

lib/mlton/basic/list.sig
lib/mlton/basic/list.sml
lib/mlton/basic/parse.sml
lib/mlton/basic/ref.sig
lib/mlton/basic/ref.sml
lib/mlton/lattice/flat-lattice.fun
lib/mlton/lattice/flat-lattice.sig
lib/mlton/lattice/sources.cm
lib/mlton/lattice/sources.mlb
lib/mlton/sources.cm
lib/mlton/sources.mlb
mlton/atoms/c-symbol.fun
mlton/atoms/id.fun
mlton/atoms/word-x-vector.fun
mlton/atoms/word-x-vector.sig
mlton/backend/machine.fun
mlton/backend/rssa-simplify.fun
mlton/control/control-flags.sig
mlton/control/control-flags.sml
mlton/control/control.sig
mlton/control/control.sml
mlton/main/compile.fun
mlton/main/main.fun
mlton/ssa/constant-propagation.fun
mlton/ssa/simplify.fun
mlton/ssa/simplify2.fun
mlton/ssa/useless.fun
mlton/xml/polyvariance.fun
mlton/xml/sxml-simplify.fun
mlton/xml/xml-simplify.fun

Various improvements to `ConstantPropagation`:
- Introduce `functor FlatLattice{Rec,Poly,Param,Mono}` and use to implement abstract values for constants, "birth", and con apps, replacing bespoke implementations.
- Use `FlatLattice{Rec,Poly,Param,Mono}.addHandler` to perform constant folding in `ConstantPropagation`.
- Use a bespoke `Sequence` lattice (which itself uses `FlatLatticeRec`) to allow fine-grained tracking of sequences with a known number of elements (up to 0w1000); in particular, this allows `WordXVector` constants to be propagated to join points of `Vector` abstract values.

Updates to ConstantPropagation

---

CHANGELOG.adoc
basis-library/primitive/prim-mlton.sml
runtime/gc/gc_state.c
runtime/gc/gc_state.h

* Fix mismatch in C and SML types for some `_import`-ed runtime functions.
* Use (default) `impure` attribute for many `_import`-ed runtime functions.

Updates to `_import`-ed runtime functions

---

CHANGELOG.adoc
mlton/ssa/constant-propagation.fun

Fix bug in `ConstantPropagation` with vector literals.

---

Makefile
doc/guide/src/CrossCompiling.adoc

There is no such target called `remote-add-cross-target`.
```console
$ make REMOTE_MACHINE=host remote-add-cross-target
make: *** No rule to make target 'remote-add-cross-target'.  Stop.
```

Fix comment in Makefile and CrossCompiling.adoc

---

bin/mlbdeps

A path of the form `./../lib/stubs/mlkit/basis/sources.mlb` should not be
normalized to `lib/stubs/mlkit/basis/sources.mlb`.

Fix `normalize_path` in `./bin/mlbdeps`

---

CHANGELOG.adoc
doc/guide/src/Bugs20210117.adoc
mlton/atoms/c-type.fun
mlton/atoms/c-type.sig
mlton/codegen/amd64-codegen/amd64-generate-transfers.fun
mlton/codegen/llvm-codegen/llvm-codegen.fun
mlton/codegen/x86-codegen/x86-generate-transfers.fun

The amd64 and LLVM codegens were not sign extending 8-bit and 16-bit arguments according to the declared C prototype when calling a C function.  While this does not seem to be required by the x86-64 SysV ABI, it is assumed by clang, which could lead to incorrect behavior when SML code called a C function compiled by clang.

Calling convention fix for amd64 and llvm codegens

---

.github/workflows/ci.yml

Use `msys2/setup-msys2` and `shell: msys2 {0}` to share CI steps between all platforms.

Fix and consolidate Windows CI

---

mlton/ssa/shrink.fun
mlton/ssa/shrink2.fun

The `numHandlerUses` was a vestige of HandlerPush/HandlerPop expressions in the
SSA IR, removed by b7a169a3a.

Remove unused `numHandlerUses` from SSA and SSA2 shrinker

---

doc/guide/src/Fold.adoc

Closes MLton/mlton#483.
Thanks to Brandon Wu (brandonspark) for the bug report.

Fix typo in Fold.adoc

---

CHANGELOG.adoc
basis-library/system/date.sml
regression/date-localOffset.ok
regression/date-localOffset.sml

Fix bug in `Date.localOffset` for time zones east of prime meridian.
Closes MLton/mlton#499.

Fix `Date.localOffset` for time zones east of prime meridian

---

CHANGELOG.adoc
mlton/codegen/amd64-codegen/amd64-allocate-registers.fun
mlton/codegen/x86-codegen/x86-allocate-registers.fun

Fix bug in x86 and amd64 native codegens leading to an internal compiler error
(`Fail: amd64AllocateRegisters.RegisterAllocation.toAddressMemLoc:disp`).
Thanks to Darin Minamoto (DarinM223) for the bug report.
Closes MLton/mlton#509

Fix `RegisterAllocation.toAddressMemLoc:disp` internal compiler error

---

lib/stubs/smlnj/basis/sources.cm

Closes MLton/mlton#523
Although SML/NJ 110.99.3 fixed some issues with `structure Real{,64}` failing to match the SML Basis Library specification, it did not implement `Real.fmt StringCvt.EXACT`.  So, a "fixed" version of `structure Real64` needs to be exported (rather than exposing the version of `structure Real64` from `$/basis.cm`) and it is simplest to revert back to `structure Real64 = Real` (where `structure Real = FixReal(struct open Pervasive.Real end)`).

Use "fixed" `structure Real64` with recent versions of SML/NJ

---

mlton/Makefile

The `ml-makedepend` invocation should use `$(MLTON_OUTPUT_SMLNJ_HEAP)` as the target, rather than `$@` (which corresponds to `$(MLTON_OUTPUT_SMLNJ_HEAP).d`).

Correct target in generated $(MLTON_OUTPUT_SMLNJ_HEAP).d file

---

README.adoc
bin/mlton-script
bin/static-library

This removes mltons runtime bash dependency and uses only portable shell script instead. Bash is still needed for building.
Benefits are:
* Packagers of mlton may not notice the bash dependency because they happen to have bash installed anyway, so their mlton package runs fine for them, but will break for somebody else who does not have bash installed.
* Simplifies installation of binary distribution, for example in minimal docker containers where bash is not preinstalled.
* Smaller downloads and disk space requirement for users who do not already use bash.
* More easily portable to new platforms where bash may not be available at all which is very desirable for a compiler.

Eliminate runtime bash dependency

---

mlton/codegen/x86-codegen/x86-generate-transfers.fun

Commit 286a54cc0 introduced a dependency on the declared prototype of a C function when generating the assembly for a C function call, in order to properly sign extend 8-bit and 16-bit arguments.
Early in the x86 codegen, Word64 values are converted into pairs of Word32 values, so a C function call with Word64 values will converted to a call with pairs of Word32 values for those arguments (increasing the number of arguments relative to the earlier IRs).  But, no such translation was made to the C function's prototype, which continued to use Int64 and Word64 types.  This lead to a `Fail: fold2` internal-compiler error due to the mismatch in the number of actual arguments and the number of prototype arguments.
A simple solution is to expand the Int64 and Word64 prototype arguments to pairs …

Fix bug in X86GenerateTransfers introduced by 286a54cc0.

---

mlton/codegen/x86-codegen/x86-allocate-registers.fun

The x86 register allocator for the floating-point stack for a simple float-to-float move tries to optimize for the common case of moving from an allocated but to-be-removed memloc by simply reassigning the floating-point stack slot to the destination.  However, this was mistakenly done before performing the register-allocation "pre" work, which had a number of unfortunate side effects.
Since the destination memloc has not been written to memory, its newly assigned floating-point stack slot is marked "not synchronized".  The subsequent "pre" work would redundantly save the destination to memory in order to "synchronize". This is redundant, because the float-to-float move is typically the first step of performing a floating-point operation (remember, in x86 assembly, a source operand is …

Bug with x86 register allocation of floating-point stack

---

bin/mlton-script
doc/guide/src/CompileTimeOptions.adoc
doc/guide/src/LLVMCodegen.adoc
man/mlton.1
mlton/main/main.fun

Update LLVM codegen documentation, noting how to specify executables for LLVM command-line tools and the required LLVM versions for MLton 20210117 and current development.

LLVM codegen documentation

---

bin/mlton-script

Add a `-target-link-opt` for OpenBSD that disables "xonly" text.
OpenBSD's linker, by default, makes a program's text segment executable-only ("xonly"): that is, executable but not readable. However, MLton needs to be able to read the text segment when mapping return addresses to stack frame indices, possibly among other things.  This causes programs compiled with MLton's native code generator to fault and die with `SIGSEGV`.
However, the default "xonly" behavior can be disabled with a linker option (`--no-execute-only`), so we can turn it off with a `-target-link-opt` specific to OpenBSD in `mlton-script`. Binaries built in this configuration run as expected.
Fixes #538

mlton-script: OpenBSD link-opt for no xonly text

---

.github/workflows/ci.yml

`macos-latest` has switched to `macos-14` (`arm64`), which will be nice to use, but will require some additional updates.

Switch from `macos-latest` to `macos-13`

---

CHANGELOG.adoc
mlton/front-end/ml.lex
mlton/front-end/ml.lex.sml.boot
mlton/front-end/mlb.lex
mlton/front-end/mlb.lex.sml.boot

Prior to a2606d0, MLton (in concert with SML/NJ) accepted line directives like:
(*#line 407 "lazyparse.nw"*)
with an implicit column of 1.  With a2606d0, the lexer was refactored and mistakenly changed to require a column number.
Thanks to Norman Ramsey for the bug report.
Closes MLton/mlton#557.

Fix regression in `#line` directives

---

runtime/gc/translate.c

It is valid for an object pointer to point to the "end" of the heap (`s->heap.start + s->heap.oldGenSize`) if it is a pointer to an object of zero size, such as a zero-length array/vector or a `unit array` or `unit ref`, in which case the object proper does not extend beyond the "end" of heap.
Closes MLton/mlton#560

Fix bug in heap translation

---

mlton/ssa/useless.fun

Allow a `Exp.Const (Const.WordXVector ws)` to "optimize" to a `Vector_vector[unit](unitVar, ..., unitVar)` when the elements are useless.

Improve/fix handling of WordXVector constants in Useless pass

---

Makefile
Makefile.binary
bin/mlton-script
bin/regression
runtime/basis/Real/IEEEReal-consts.c
runtime/gc/gc_state.h
runtime/gc/init.c
runtime/gc/profiling.h
runtime/gc/signals.c
runtime/gc/signals.h

This was split off of #550.
- Two of these fix some minor compiler warnings.
- One automates rounding mode detection (WASM only supports the 1 rounding mode, and it turns out POSIX already provides a mechanism to detect this).
- The last three commits make it easier to build and install multiple cross-compiler targets at the same time.

A handful of improvements related to cross compiling

---

CHANGELOG.adoc
doc/guide/src/LLVMCodegen.adoc
mlton/codegen/llvm-codegen/llvm-codegen.fun

Update the LLVM codegen to generate LLVM IR using opaque pointers; using the LLVM codegen requires LLVM 15 (or higher).

LLVM opaque pointers

---

mlton/control/control-flags.sig
mlton/control/control-flags.sml
mlton/main/main.fun
mlton/ssa/introduce-loops.fun
mlton/ssa/shrink.fun
mlton/ssa/shrink2.fun
mlton/ssa/ssa-tree.fun
mlton/ssa/ssa-tree.sig

Add `-profile-tail-call-opt {true|false}` expert compile-time option.  The `-profile-tail-call-opt {true|false}` controls whether or not the SSA{,2} shrinker optimizes tail calls in the presence of profiling.
Add `-profile-tail-call-opt {true|false}` expert compile-time option.  The `-profile-intro-loops-opt {true|false}` controls whether or not the SSA IntroduceLoops optimization applies in presence of profiling and `-profile-tail-call-opt false`, when the SSA{,2} shrinker does not optimize tail calls in the presence of profiling.  In particular, when `-profile-tail-call-opt false` but `-profile-intro-loops-opt true`, then IntroduceLoops will recognize self non-tail calls with eta return and handler continuations as tail calls.
`-profile-tail-call-opt false` and `-profile-intro-loops-opt …

Introduce options to control profiling-specific optimizations

---

doc/guide/src/References.adoc

The previous link returned a 404. 
https://community.haskell.org/~simonmar/papers/async.pdf
The new link is hosted on GitHub pages, apparently by one of the authors. 
https://simonmar.github.io/bib/papers/async.pdf

Replace broken link to 'Asynchronous Exceptions in Haskell' paper
