MLton/mlton

Makefile, mlton/Makefile
I am really sorry for inattention: my first patch was incorrect.
=> Fixed LANG variable.

mlton/control/control-flags.sig, mlton/control/control-flags.sml, mlton/control/source.sig, mlton/control/source.sml, mlton/front-end/front-end.fun, mlton/front-end/mlb-front-end.fun, mlton/main/compile.fun, mlton/main/main.fun
Implemented the keep-ast command line feature.
=> Implement keep-ast feature.

util/cm2mlb/cm2mlb.sml
The cm2mlb "-map file" option allows setting a mapping from CM anchors
to MLB paths in order to generate MLB files with MLB paths that
correspond to CM anchors.
However, it is sometimes necessary to specify a CM anchor environment
in order for CM.Graph.graph to properly process a .cm file.  For
example:
devel.cm:
```
Library
structure Lib
is
sources.cm (bind:(anchor:util value:wip/util))
```
sources.cm:
```
Library
structure Lib
is
$util/sources.cm
lib.sml
```
In order to process sources.cm with cm2mlb, a binding for $util is
necessary for CM.Graph.graph to process.  While a binding for $util is
provided by devel.cm, processing devel.cm with cm2mlb will simply
result in a MLB file with a reference to sources.mlb.
The cm2mlb "-bind file" option allows setting a binding from CM
anchors to …
=> Add support for setting CM anchor bindings in cm2mlb tool

mlton/main/main.fun
Closes https://github.com/MLton/mlton/issues/148
=> Generate position independent code for OpenBSD

mlton/atoms/prim.fun
See discussion at
https://sourceforge.net/p/mlton/mailman/message/34493424/.
Closes MLton/mlton#119.
=> Constant fold CPointer_equal(NULL, NULL) to true

mlton/atoms/prim.fun, mlton/atoms/prim.sig, mlton/backend/ssa-to-rssa.fun, mlton/ssa/useless.fun
Updated a few Prims to facilitate new functionality. This will likely need to be review and will need more changes.
The sizing stuff appears to be in this as well, but I haven't made any changes to that.
=> Word array prims

mlton/backend/allocate-registers.fun, mlton/backend/allocate-registers.sig, mlton/backend/backend.fun
Highlights:
* Improve `Allocation.Stack.get` (31b6e29)
* Do not force Cont block arguments to stack (7ec42a1)
=> Misc. updates to stack management in backend

doc/guide/src/Bugs20180206.adoc, doc/guide/src/Bugs20180207.adoc, doc/guide/src/Contact.adoc, doc/guide/src/Home.adoc, doc/guide/src/Release20180207.adoc, doc/guide/src/Releases.adoc
Final work for 20180207 release.
=> Pre 201802 release

mlton/backend/rssa.fun
The start block could also be converted to one which may need be replaced.
=> Fix rssa shrink issue brought up by rssa bounce changes

lib/mlton/basic/hash-set.sig, lib/mlton/basic/hash-set.sml, mlton/atoms/hash-type.fun, mlton/atoms/hash-type.sig, mlton/backend/packed-representation.fun, mlton/backend/representation.sig, mlton/backend/ssa2-to-rssa.fun, mlton/closure-convert/closure-convert.fun, mlton/control/control-flags.sig, mlton/control/control-flags.sml, mlton/main/main.fun, mlton/ssa/simplify.fun, mlton/ssa/simplify2.fun, mlton/ssa/ssa-to-ssa2.fun, mlton/ssa/ssa-tree.fun, mlton/ssa/ssa-tree.sig, mlton/ssa/ssa-tree2.fun, mlton/ssa/ssa-tree2.sig, mlton/xml/sxml-simplify.fun, mlton/xml/xml-simplify.fun
See MLton/mlton#334, 85148aa, and 2b7a560.
After converting from one IR to the next, all global data associated with the previous IR should be dead.  However, it was observed that the tables used for hash-consing of types were retained after converting from the corresponding IR.  Similarly, some properties attached to `Ssa2.Tycon.t`, `Ssa2.Con.t`, and `Ssa2.Type.t` during `PackedRepresentation` were not dead after converting to RSSA.
The `ControlFlags.optimizationPasses` reference was retaining references to the IR-specific data, because it contained closures that references IR_specific optimization passes.  Moreover, the `ControlFlags.optimizationPasses` reference was retained by the global `{name: string, value: (unit -> string)} list ref` used to implement `Control.all()`.
This PR …
=> Avoid capturing IR-specific closures in global list of control flags

.travis.yml
See https://docs.travis-ci.com/user/build-config-validation
=> Updates for TravisCI build config validation

basis-library/mlton/call-stack.sml, mlton/backend/ssa2-to-rssa.fun
Accidentally dropped from #340.
=> Fix whitespace

mlton/ssa/split-types.fun
This has been bugging me for a while but I never got around to trying to fix it:
Before, the fresh types were hashed only by tycon,
so were put into rather large buckets. They now generate hashes.
Compile time is improved marginally; this would probably make more of an impact with tuples as datatypes in https://github.com/MLton/mlton/issues/329
I can't seem to get newFresh and the like to fit nicely into a structure because of the mutual recursion.
=> Minor compile-time improvement: Improve split-types HashTable performance

mlton/ssa/simplify-types.fun
The previous "simplifying" of `SimplifyTypes` was overzealous.  It ended up eliminating the aspects of the transformation that cleaned up types of cardinality 1; such types are equivalent (and many become translated) to `unit` and should be removed from types, arguments, etc.
=> Fix regression in functionality of `SimplifyTypes`.

mlton/backend/rssa-shrink.fun
MLton/mlton#298 introduced a (simple) jump optimization in `RssaShrink`.  However, an infinite loop block like
loop_61 () Jump =
loop_61 ()
would lead to an infinite loop in `RssaShrink` trying to compute the replacement label for `loop_61`.
To avoid the infinite loop, we pre-calculate the replacement label for each block, keeping track of labels seen and marking the looping block as having no replacement.
Closes MLton/mlton#372
=> Fix infinite loop with jump chaining in `RssaShrink`

doc/guide/src/ConcurrentMLImplementation.adoc, lib/cml/core-cml/event.sml
=> Tweak critical section management for executing `blockFns`

package/nix/default.nix
=> Add a Nix build script

doc/guide/src/MLRISCLibrary.adoc, doc/guide/src/Release20200817.adoc, doc/guide/src/SMLNJLibrary.adoc
* Update `SMLNJLibrary` and `MLRISCLibrary` pages in guide
* Add contributed MinGW binary packages
=> Guide updates

Makefile
Motivated by downstream changes in MaPLe fork that wants to omit building tools.
=> Minor tweaks to `Makefile`

CHANGELOG.adoc, bin/mlton-script, bin/platform, mlton/control/control-flags.sml, runtime/platform/darwin.c
Thanks to Chris Cannam for the patches.
See discussion at: https://sourceforge.net/p/mlton/mailman/mlton-user/thread/d40764ee-7d1b-41e0-a101-caafe3483879%40www.fastmail.com/#msg37185161
=> Preliminary support for arm64-darwin (Apple Silicon)

Makefile, Makefile.binary
please have a look at the commit messages for the details
=> build fixes

.github/workflows/ci.yml
~~I couldn't build the head of master locally, I got some error about it using `struct GC_profileLabelInfo` which was removed recently. So I have tested it against commit f8c00b04d097a5c2b4d24091902ad751045d041a, before that was merged.~~ I got it building on HEAD. 
It fails `real`, but all other tests pass.
=> Add workflow for Windows

CHANGELOG.adoc, doc/guide/src/Bugs20210117.adoc, mlton/backend/allocate-variables.fun, mlton/backend/allocate-variables.sig, mlton/backend/backend.fun, mlton/backend/machine.fun, mlton/backend/machine.sig, mlton/backend/runtime.fun, mlton/codegen/amd64-codegen/amd64-translate.fun, mlton/codegen/c-codegen/c-codegen.fun, mlton/codegen/llvm-codegen/llvm-codegen.fun, mlton/codegen/x86-codegen/x86-translate.fun, runtime/gc/gc_state.h, runtime/gc/profiling.c
=> Fix bug with `-profile time` leading to a segmentation fault.

CHANGELOG.adoc, runtime/gc/invariant.c, runtime/gc/sequence.c
Thanks to Chris Cannam for the bug report and debugging.
=> Fix bug in GC_sequenceCopy failing to update card map

LICENSE, mlton/ssa/ssa-tree2.fun
* Update Copyright year in LICENSE
* Fix file names for SSA2 dot output
=> Misc updates

mlton/backend/backend.fun, mlton/backend/machine.fun, mlton/backend/machine.sig, runtime/gc/frame.h, runtime/gc/profiling.c
Split `ML_FRAME` into `{CONT,FUNC,HANDLER}_FRAME` kinds and rename `C_FRAME` to `CRETURN_FRAME` kind.
=> Extend `Machine.FrameInfo.Kind` and `GC_frameKind`

bin/mlton-script, bin/platform
@MatthewFluet Could we add these?
=> mlton-script: support powerpc-darwin

mlton/backend/allocate-variables.fun
=> Fix `Backend` bug in allocation of `handlerOffset` and `handlerArgs`

mlton/backend/packed-representation.fun, mlton/backend/rep-type.fun, mlton/control/bits.sml, mlton/main/compile.fun, runtime/gc/mark-compact.c
See details in be6ed548f859de09bf273f1d31d62dcb256c7561.
=> Mark-Compact GC bug with `-align 4`

basis-library/io/imperative-io.fun, regression/textio.3.sml
See 3d19b9368bf88c8aab69f26fdf270dd2c2c9f97d for details.
Fixes MLton/mlton#535
=> Fix bug in `ImperativeIO(...).getInstream`

basis-library/mlton/platform.sig, basis-library/mlton/platform.sml, bin/platform, runtime/cenv.h, runtime/platform/loongarch64.h
I have port this , but I'm still bootstrap it .If It can works , I'll update the test result
=> Add LoongArch64 support

doc/guide/src/SSASimplify.adoc
Leads to broken LoopUnfoll link at http://mlton.org/SSASimplify
=> Fix broken link in SSASimplify.adoc

mlton/backend/rssa-tree.fun, mlton/backend/rssa-tree.sig, mlton/ssa/ssa-tree.fun, mlton/ssa/ssa-tree2.fun
Minor updates to SSA IR infrastructure; in particular, general control-flow and dot files for RSSA.
=> {Ssa,Ssa2,Rssa} infrastructure

runtime/basis/MLton/Process/spawne.c, runtime/basis/MLton/Process/spawnp.c, runtime/basis/Net/Socket/Socket.c, runtime/basis/Posix/Process/exece.c, runtime/basis/Posix/Process/execp.c, runtime/platform.h, runtime/platform/mingw.h
Various updates to quell compilation errors with new MinGW prototypes for POSIX functions.
=> MinGW prototypes update

mlton/Makefile
Please see #601 for an explanation.
=> fix #601: use 'chmod a-w' instead of 'chmod -w'

doc/guide/src/SMLSharp.adoc
Fix and delete several broken links in doc about SML#.
=> Fix and delete several broken links in doc

CHANGELOG.adoc, mlton/ssa/useless.fun, regression/dfa-gen.sml
Make `Array_alloc` arg useful when result array's length is useful
Closes MLton/mlton#622.
=> Fix bug in Useless optimization
